### ISSUE TITLE
Whether or not an icon is set, there will be a margin on the left, whether the margin can be removed

### ISSUE THREAD

**Issue by xiaowine** [Maxr1998/ModernAndroidPreferences#141]

**Comment by Maxr1998** [comment]
Set [`collapseIcon = true`](https://github.com/Maxr1998/ModernAndroidPreferences/blob/c6ab337cc9e3dbeffe9d7636171a595772d2261e/library/src/main/java/de/Maxr1998/modernpreferences/Preferences.kt#L491) on the PreferenceScreen.

**Comment by xiaowine** [comment]
> Set [`collapseIcon = true`](https://github.com/Maxr1998/ModernAndroidPreferences/blob/c6ab337cc9e3dbeffe9d7636171a595772d2261e/library/src/main/java/de/Maxr1998/modernpreferences/Preferences.kt#L491) on the PreferenceScreen.

thanks
