### ISSUE TITLE
Add option to show multiline preference titles

### ISSUE THREAD

**Issue by 8bitPit** [Maxr1998/ModernAndroidPreferences#3]
Right now, preference titles can get cut off pretty quickly if the user set their display or font size to 'large', especially switch preference titles (see screenshot below). Note: Preferences are padded with (2x) 8dp horizontal padding.
![image](https://user-images.githubusercontent.com/9284845/100261955-c808ba80-2f4b-11eb-9fba-a76989929e3f.png)

**Comment by Maxr1998** [comment]
Implemented in 1.1.0-beta1. It can be configured through `Preference.Config` now.
