### ISSUE TITLE
Implement an `EditTextPreference` counterpart

### ISSUE THREAD

**Issue by msfjarvis** [Maxr1998/ModernAndroidPreferences#4]
`androidx.preference` provides [EditTextPreference](https://developer.android.com/reference/kotlin/androidx/preference/EditTextPreference) as a way to accept arbitrary text input from users, which has no parallel in ModernAndroidPreference as of now.

It'd also be great to be able to have an optional validator method that would be called when the user attempts to save the value, and possibly a way to provide `inputType` flags for the underlying `EditText` so we can enforce things like numeric input without needing the validator or inconveniencing the user.

**Comment by msfjarvis** [comment]
Shipped in 1.2.0-alpha1 so probably okay to close now

**Comment by Maxr1998** [comment]
Yep, closing this now.
