### ISSUE TITLE
Setting `collapseIcon = true` does not work

### ISSUE THREAD

**Issue by msfjarvis** [Maxr1998/ModernAndroidPreferences#44]
The logic in [this line](https://github.com/Maxr1998/ModernAndroidPreferences/blob/cb7b344dbea768e385b17a18feee738e0fb171fd/library/src/main/java/de/Maxr1998/modernpreferences/Preferences.kt#L206) is never `false`.

Setting a breakpoint confirms this. The expression evaluates to `false` in this case even though there is no `iconRes` or `icon` set.

![Screenshot of the line of code linked above with a debugger expression evaluation for 'itemVisible || !preferenceParent.collapseIcon' which results in 'false'](https://user-images.githubusercontent.com/13348378/179222018-f4375595-8359-49ba-a5e2-bd98658a707a.png)

![Screenshot of the line of code linked above with a debugger expression evaluation for 'iconRes != DEFAULT_RES_ID || icon != null' which results in 'false'](https://user-images.githubusercontent.com/13348378/179222177-d1c7ab1c-700b-43ff-a4b9-ccb07bf80cd3.png)

**Comment by Maxr1998** [comment]
Could you check if `collapseIcon` is actually true there? I just tested this locally, and it seemed to work.
Note that the `collapseIcon` attribute currently has to be set on every `screen`/`subScreen` and isn't inherited from the parent screen.

**Comment by msfjarvis** [comment]
> Note that the `collapseIcon` attribute currently has to be set on every `screen`/`subScreen` and isn't inherited from the parent screen.

_Oh_

That was it, thanks!

**Comment by Maxr1998** [comment]
Alright, good to know it's not a bug.
But this shows me the current design is neither obvious nor that great. I'll look if I can tune this for a future release. I think when I finally introduce the storage abstraction, I could also include a few other behavior changes as part of a major release.
