### ISSUE TITLE
multiChoice preference doesn't show summary

### ISSUE THREAD

**Issue by rosenpin** [Maxr1998/ModernAndroidPreferences#7]
Hi Max what's up?
Long time

This library is pretty awesome, it looks fantastic and this is the least painful way I encountered to handle preferences in Android

I messed around a bit with it in a new app I'm working on and it seems like when providing summary to the multiChoice preference it isn't shown anywhere, not where the normal summaries are and not in the dialog

Code:
``` kotlin
 multiChoice("special_buttons", specialButtons) {
            title = "Special buttons"
            summary = "WIP: Choose what the special button to show"
        }
```

Thanks!

**Comment by Maxr1998** [comment]
Hey Tomer,
Long time no see!
Hope you're doing good, glad to see that Always On AMOLED is still getting updated.

So, onto your report: the choice preferences are currently set up to show the current selection if one was made, and only fall back to the standard summaries if you made no choice at all. This is less than ideal, and I should fix that.
I'll probably handle it like I do in the new EditText preference, and allow the use of a [summary provider lambda](https://github.com/Maxr1998/ModernAndroidPreferences/blob/29f9b539b822923b4a4583d69f9829efec68e79d/library/src/main/java/de/Maxr1998/modernpreferences/preferences/EditTextPreference.kt#L35), with a fallback to the current behavior.
And you're right, it also makes sense to show not only the preference title, but also the summary within dialogs (possibly configurable).

**Comment by rosenpin** [comment]
Thanks! :)

Awesome, sounds great

Though I should note that I didn't see the summary even before making a selection. Same if I clear the app data, it just stays empty

**Comment by Maxr1998** [comment]
> Though I should note that I didn't see the summary even before making a selection. Same if I clear the app data, it just stays empty

I have to investigate this then :thinking:

**Comment by Maxr1998** [comment]
Should be working actually, at least I couldn't reproduce the bug.
Regardless, I introduce the possibility to turn of auto-generated summaries in 7780c3d249db24d0538cc5293a1df9ea759630cb. You simply have to set `autoGeneratedSummary` to false on the preference.

I'll draft a new release soon, then you can test it. Sorry for taking so long, university work really kept me busy..
